#!/bin/bash
# agocontrol postinst script
PASSWD=letmein

if ! getent passwd agocontrol > /dev/null ; then
    echo 'Adding system-user for agocontrol' 1>&2
    adduser --system --home /var/run/agocontrol --group --disabled-password agocontrol
    adduser agocontrol dialout
    mkdir -p /var/run/agocontrol
    mkdir -p /var/crash
    chown agocontrol:agocontrol /var/run/agocontrol
fi

grep "00000000-0000-0000-000000000000" /etc/opt/agocontrol/conf.d/system.conf && (
	UUID=$(uuidgen)
	sed -i "s/00000000-0000-0000-000000000000/${UUID}/" /etc/opt/agocontrol/conf.d/system.conf
)

test -e /etc/opt/agocontrol/db/inventory.db || (
	test -e /etc/opt/agocontrol/inventory.db && (mv /etc/opt/agocontrol/inventory.db /etc/opt/agocontrol/db/inventory.db) || (
		sqlite3 -init /var/opt/agocontrol/inventory.sql /etc/opt/agocontrol/db/inventory.db .quit | tee
	)
)

SASLDB=$(grep sasldb_path /etc/sasl2/qpidd.conf | cut -d ":" -f 2)

sasldblistusers2 -f $SASLDB | grep -q agocontrol || (
    SASLDBPATH=$(dirname $SASLDB)
    mkdir -p $SASLDBPATH
	echo $PASSWD | saslpasswd2 -c -p -f $SASLDB -u QPID agocontrol
)

grep -q agocontrol /etc/qpid/qpidd.acl || (
	sed -i 's/admin@QPID/admin@QPID agocontrol@QPID/g' /etc/qpid/qpidd.acl
	chown .qpidd /etc/qpid/qpidd.acl
	invoke-rc.d qpidd restart
)

if [ ! -d /etc/opt/agocontrol/ui ]; then
   mkdir -p /etc/opt/agocontrol/ui
fi

chown -R agocontrol:agocontrol /etc/opt/agocontrol

# install datalogger 
if [ ! -d "/var/opt/agocontrol" ]; then
   mkdir -p /var/opt/agocontrol
fi

test -e /var/opt/agocontrol/datalogger.db || (
	sqlite3 -init /var/opt/agocontrol/datalogger.sql /var/opt/agocontrol/datalogger.db .quit | tee
)

chown -R agocontrol:agocontrol /var/opt/agocontrol


