commands:
  "allon":
    name: turn all on
  "alloff":
    name: turn all off
  push:
    name: push button
  settemperature:
    name: set temperature
    parameters:
      temperature:
        name: temperature to set
        type: float
      mode:
        name: setpoint mode
        type: option
        options: ["auto", "cool", "heat"]
  setthermostatmode:
    name: adjust thermostat mode
    parameters:
      mode:
        name: thermostat mode to set
        type: option
        options: ["heat", "cool", "auto"]
  setthermostatfanmode:
    name: adjust thermostat fan mode
    parameters:
      mode:
        name: fan mode to set
        type: option
        options: ["on", "off", "auto"]
  dial:
    name: dial number
    parameters:
      number:
        name: number to dial
        type: string
  setlevel:
    name: set level
    parameters:
      level:
        name: level to set
        type: integer
        range: [0, 100]
  fade:
    name: fade to a level with a timed delay
    parameters:
      level:
        name: level to set
        type: integer
        range: [0, 100]
      time:
        name: time slope for setting the level, milli seconds
        type: integer
        range: [0, 4294967296]
  setfadetime:
    name: set time (in ms) to be used for setlevel commands
    parameters:
      time:
        name: time slope for setting the level, milli seconds
        type: integer
        range: [0, 4294967296]
  setchannel:
    name: set channel
    parameters:
      channel:
        name: channel to set
        type: integer
        range: [0, 9999]
  setcolor:
    name: set color
    parameters:
      red:
        name: level for red color
        type: integer
        range: [0, 100]
      green:
        name: level for green color
        type: integer
        range: [0, 100]
      blue:
        name: level for blue color
        type: integer
        range: [0, 100]
  sethue:
    name: set hue (colour)
    parameters:
      level:
        name: level to set
        type: integer
        range: [0, 65535]
  setsaturation:
    name: set saturation (color)
    parameters:
      level:
        name: level to set
        type: integer
        range: [0, 65535]
  setcolortemp:
    name: set color temperature (color)
    parameters:
      level:
        name: level to set (K)
        type: integer
        range: [0, 65535]
  sendir:
    name: send infrared remote code
    parameters:
      ircode:
        name: infrared code to send
        type: string
  triggeralarm:
    name: triggers an alarm
    parameters:
      duration:
        name: duration in seconds
        type: integer
      cause:
        name: cause of alarm
        type: string
      description:
        name: description of alarm
        type: string
      detail:
        name: more detail about alaram
        type: string
      importance:
        name: numeric value that indicates how important the alarm is.
        type: integer
  clearalarm:
    name: clears an alarm
devicetypes:
  pushbutton:
    name: Pushbutton
    description: momentary switch
    commands: [push]
    events: [event.device.push, event.device.doublepush, event.device.triplepush]
  hdmicec:
    name: HDMI CEC interface
    description: control devices on the HDMI bus
    commands: [alloff]
  infaredblaster:
    name: infraredblaster
    description: send infrared remote commands
    commands: [sendir]
  phone:
    name: telephone
    description: a phone
    commands: [dial]
  powermeter:
    name: power meter
    description: sensor for power utilisation
    commands: []
  energycounter:
    name: energy counter 
    description: coutner for energy consumption
    commands: []
  energymeter:
    name: energy meter
    description: sensor for current energy level
    commands: []
  flowmeter:
    name: flow meter
    description: sensor for water/gas flow
    commands: []
  binarysensor:
    name: binary sensor
    description: sensor for on off values
    commands: []
  multilevelsensor:
    name: multilevel sensor
    description: sensor for multilevel values
    commands: [reset]
  temperaturesensor:
    name: temperature sensor
    description: sensor for temperature levels
    commands: []
  humiditysensor:
    name: humidity sensor
    description: sensor for humidity levels
    commands: []
  brightnesssensor:
    name: brightness sensor
    description: sensor for brightness levels
    commands: []
  batterysensor:
    name: battery sensor
    description: sensor for battery levels
    commands: []
  barometersensor:
    name: barometric sensor
    description: sensor for barometric levels
    commands: []
  windsensor:
    name: windspeed sensor
    description: sensor for wind speed
    commands: []
  rainsensor:
    name: rain sensor
    description: sensor for rain
    commands: []
  uvsensor:
    name: UV sensor
    description: sensor for UV radiation
    commands: []
  co2sensor:
    name: CO2 sensor
    description: sensor for CO2 levels
    commands: []
  airqualitysensor:
    name: air quality sensor
    description: sensor for air quality
    commands: []
  smokedetector:
    name: smoke detector
    description: smoke detector
    commands: []
  dimmerrgb:
    name: RGB dimmer
    description: allows to set different colors
    commands: ["on", "off", setlevel, setcolor]
  smartdimmer:
    name: Dimmer with more advanced features
    description: Bulb with integrated WiFi. Allows to set different colors and beyond
    commands: ["on", "off", setlevel, fade, setfadetime, setcolor, sethue, setsaturation, setcolortemp]
  controller:
    name: controller
    description: generic controller
    commands: []
  thermostat:
    name: thermostat
    description: controls temperature
    commands: [settemperature, setthermostatmode, setthermostatfanmode]
  drapes:
    name: drapes
    description: window drapes or blinds
    commands: ["on", "off", stop, setlevel]
  dimmer:
    name: dimmer
    description: light dimmmer
    commands: ["on", "off", setlevel]
  switch:
    name: switch
    description: simple on off switch
    commands: ["on", "off"]
  computer:
    name: General computer (for Wake on LAN)
    description: A computer
    commands: ["on"]
values:
  level:
    name: level
    description: level value
  callerid:
    name: caller identity
    description: the identity of a caller
  extension:
    name: phone extension
    description: extension being called
  data:
    name: data
    description: data field
  scene:
    name: scene
    description: the scene number
    type: integer
events:
  event.telecom.call:
    description: a call is originating
    parameters: [uuid, callerid, extension]
  event.telecom.hangup:
    description: call hung up
    parameters: [uuid]
  event.device.scenechanged:
    description: announces a scene change
    parameters: [scene, uuid]
  event.environment.counterchanged:
    description: counter has changed
    parameters: [level, uuid]
  event.environment.temperaturechanged:
    description: temperature has changed
    parameters: [level, unit, uuid]
  event.environment.brightnesschanged:
    description: brightness has changed
    parameters: [level, unit, uuid]
  event.environment.humiditychanged:
    description: humidity has changed
    parameters: [level, unit, uuid]
  event.security.sensortriggered:
    description: sensor was triggererd
    parameters: [level, uuid]
  event.environment.powerchanged:
    description: power level has changed
    parameters: [level, uuid]
  event.environment.energychanged:
    description: energy level has changed
    parameters: [level, uuid]
  event.environment.flowchanged:
    description: flow has changed
    parameters: [level, uuid]
  event.environment.counterchanged:
    description: counter value has changed
    parameters: [level, uuid]
  event.proximity.ndef:
    description: NFC NDEF tag within range
    parameters: [data]
  event.device.distancechanged:
    description: distance from sensor has changed
    parameters: [level, unit, uuid]
  event.environment.forecastchanged:
    description: forecast from sensor has changed
    parameters: [forecast, uuid]
  event.device.batterylevelchanged:
    description: battery level has changed
    parameters: [level, unit, uuid]
  event.environment.coolsetpointchanged:
    description: cool set point has changed
    parameters: [level, unit, uuid]
  event.environment.heatsetpointchanged:
    description: heat set point has changed
    parameters: [level, unit, uuid]
  event.environment.powerchanged:
    description: power usage has changed
    parameters: [level, unit, uuid]
  event.environment.fanmodechanged:
    description: fan mode has changed
    parameters: [level, unit, uuid]
  event.environment.modechanged:
    description: thermostat mode has changed
    parameters: [level, unit, uuid]
  event.environment.fanstatechanged:
    description: fan state has changed
    parameters: [level, unit, uuid]
  event.environment.co2changed:
    description: CO2 level has changed
    parameters: [level, unit, uuid]
  event.device.push:
    description: single push
    parameters: [uuid]
  event.device.doublepush:
    description: double push
    parameters: [uuid]
  event.device.triplepush:
    description: triple push
    parameters: [uuid]
units:
  degC:
    label: "°C"
    description: degree celcius
  degF:
    label: "°F"
    description: degree farenheit
  percent:
    label: "%"
    description: percent value
  lux:
    label: "lux"
    description: brighness in lux
  m:
    label: "meters"
    description: distance in meters
  inch:
    label: "inches"
    description: distance in inches
  A:
    label: "A"
    description: Intensity in Ampere
  V:
    label: "V"
    description: Voltage in Volt
  kWh:
    label: "kWh"
    description: Power in kilowatt hour
  Wh:
    label: "Wh"
    description: Power in watt hour
  lh:
    label: "l/h"
    description: flow in liter per hour
  ms:
    label: "m/s"
    description: Speed in meter per seconds